/** Plain-language help, not a second financial calculation engine. */
export type Guide = { title: string; items: [string, string][] };

export const SCREEN_GUIDES: Record<string, Guide> = {
  dashboard: { title: "Your dashboard", items: [
    ["Safe to spend", "Cash minus unpaid commitments, your protected cash buffer and outstanding goal contributions. A negative figure is a plan shortfall, not necessarily an overdraft. Click the number for the actual calculation."],
    ["Safe to spend today", "The smallest daily allowance across your open budgets. Each allowance is capped by what your available cash supports; it is not extra money on top of your balance."],
    ["Projected month-end savings", "A planning projection, not money already saved. Flexible goals may be reduced; an unaffordable protected goal can still appear in the projection. Open the number to check its shortfall."],
    ["Net worth and account balances", "Net worth includes recorded bank, cash, savings and investments, less debt. It is not all spendable cash. An account balance is its starting balance plus posted movements."],
    ["Next major commitment", "The next recorded outflow on the calendar. No recorded commitment does not mean you have no bills—missing due dates cannot be forecast."],
    ["Cash runway", "Current cash plus expected income minus recorded committed payments. It excludes everyday variable spending and is not a complete affordability forecast. Tap the curve or use its arrow keys to inspect a day."],
    ["Budget cards", "Spent is recorded category spending; remaining is the allowance plus rollover minus spending. A spending limit is a plan, not a funded pot. Warnings describe pace, overspending or insufficient evidence."],
  ] },
  transactions: { title: "Your transactions", items: [
    ["Add", "Record an actual expense, income, transfer or refund. Choose the real paying/receiving account. Do not record an expected payment as received."],
    ["Date, description and merchant", "The booking date controls balances and reporting periods. Description says what happened; merchant identifies who you paid or received money from."],
    ["Amount and cash effect", "Cash effect is the change to current and cash accounts. A transfer between those accounts nets to zero; a card purchase can affect spending without immediately reducing cash."],
    ["Categories and splits", "Categories decide which budget and analytics group an expense belongs to. Split an expense when one purchase covers several categories."],
    ["Edit and Void", "Edit corrects descriptions, merchants and categories. Void excludes an incorrect transaction from calculations while preserving its record; re-enter it to correct its amount or date."],
    ["Filters and pages", "Show voided includes excluded entries for review. Older/Newer navigates the transaction history, not just the current month."],
  ] },
  accounts: { title: "Your accounts and categories", items: [
    ["Balances and opening balances", "Opening balance is money held when tracking starts; transactions change it afterwards. Do not enter old purchases again if they are already reflected in that balance."],
    ["Renaming and archiving", "Renaming changes only the label; past transactions show the new name. Archive an account you have closed once its balance is zero: it leaves pickers, imports and forecasts but keeps its history, and Restore brings it back."],
    ["Account kinds", "Current and Cash supply spendable cash. Savings and Investments count toward net worth; liabilities are money owed. Income source and Expense are bookkeeping counterparties, not extra money."],
    ["Categories and defaults", "Essential/discretionary classifications inform reports. A default category is applied to new expense postings; changing it does not rewrite old spending."],
    ["Categorisation rules", "Ordered rules match descriptions or merchants. Preview before applying to history: changing categories can change past budget reports."],
    ["Bank connections", "Connect, map a bank account, then sync. Imported rows are candidates to review, not money added automatically. Revoking disconnects the feed."],
    ["Protected cash buffer", "Cash that safe to spend always holds back, such as a month of essential bills. Raising it lowers safe to spend by the same amount; the balance curve warns when a bill would dip below it."],
    ["Setup checklist", "Shows the account kinds and categories needed to enter transactions. A completed checklist does not mean all your financial information is complete."],
  ] },
  budgets: { title: "Your budgets and month plan", items: [
    ["Month plan and unassigned", "Expected income minus counted bills, budget allocations and monthly goal contributions. A bill covered by a category budget is counted once. Unassigned is planned income left to allocate, not cash in your bank."],
    ["Expected versus received income", "Expected is your estimate and schedule; received comes from posted transactions. Adding expected income never increases today's balance."],
    ["Period, dates and anchor", "Monthly means calendar month. Fortnightly and 30-day budgets use an anchor date. End date stops a budget; the month plan prorates cycles that cross month boundaries."],
    ["Spent, remaining and rollover", "Remaining = allowance + carried-in amount − net spending. Rollover chooses whether surplus or overspending carries into the next cycle."],
    ["Daily allowance and meter", "The daily number spreads the remaining allowance over days left, capped by available cash. The meter compares spending with the allowance; its pace marker shows elapsed-time expectations."],
    ["Scope and defaults", "A category scope includes that category's descendants. No scope covers discretionary spending. Account defaults categorise new expense entries."],
    ["Edit, pause and reset", "Amount edits apply from a period boundary. Pausing stops a plan; resetting rollover writes off the carry. Neither action manufactures cash or deletes transactions."],
    ["Warnings and projections", "Projections estimate where spending is heading. 'Not yet assessable' means insufficient evidence—not that the budget is safe."],
  ] },
  calendar: { title: "Your calendar", items: [
    ["Daily balance and curve", "Past dates use recorded cash movements; future dates use expected income and recorded hard commitments. Variable spending and unentered bills are not predicted."],
    ["Income and commitments", "Expected income is an estimate until posted. Hard commitments reduce safe to spend; optional commitments do not. Tap a day to inspect its events."],
    ["Amount, first due and repeats", "Amount is per occurrence. First due anchors the schedule; repeat rules generate later dates. End date stops future occurrences."],
    ["Match review", "A linked payment prevents a bill being counted twice. Confirmation clears the review queue; it does not release the same money again. Unmatch reverses an incorrect link."],
    ["Protected buffer and warnings", "The buffer is your configured cash floor. A breach warns that recorded commitments take the projected balance below that floor."],
    ["Month navigation", "Previous/Next changes the displayed calendar month, not the dates stored on your bills or transactions."],
  ] },
  goals: { title: "Your savings goals", items: [
    ["Target and progress", "Progress is money attributed to this goal divided by its target. A target is not money you already have."],
    ["Monthly contribution", "This is a plan. Outstanding contributions reduce safe to spend until recorded; setting a contribution does not transfer money."],
    ["Priority and protection", "Critical and High goals are protected by default. Flexible goals can be reduced in recovery projections; you can override protection."],
    ["Savings account and contributions", "The linked account holds the real money. A contribution attributes existing savings to a goal; it must not claim more than the account holds."],
    ["Projected completion", "An estimate based on remaining target and planned monthly contributions, not a guarantee. No monthly contribution means no estimated completion date."],
    ["One-off purchases and completion", "A purchase goal is a funding target, not a receipt. Record the actual purchase with Add. Rename or pause the goal when no longer needed; historical transactions remain."],
  ] },
  analytics: { title: "Your analytics", items: [
    ["Income", "Posted income in the selected period, not expected future payments or opening balances."],
    ["Spending", "Recorded expenses net of applicable refunds/reimbursements. Transfers between your own accounts are not ordinary spending."],
    ["Savings rate", "(Income − spending) ÷ income. This measures the surplus rate; it is not the same as money deliberately transferred into savings. With no income, the rate is undefined."],
    ["Set aside", "Recorded savings/investment movements as reported by the ledger. This differs from the unspent portion of income."],
    ["Category, merchant and monthly charts", "Group the same recorded activity by category, merchant or month. Tap or use arrow keys to inspect chart values. Missing categories appear as uncategorised."],
    ["Needs / wants / savings", "A comparison against a planning guideline, not a rule about what you must spend. Category classification affects the split."],
    ["Date range", "Changes the reporting window; it does not change the underlying transactions."],
  ] },
  insights: { title: "Your insights", items: [
    ["Observations", "Read-only findings from your recorded balances, budgets and goals. They do not move money or change your plan."],
    ["Evidence", "The dates, amounts and comparisons supporting a finding. Check these before acting, especially with a short or incomplete history."],
    ["Suggested action", "A proposal to review, not an automatic edit. Changes happen only when you make them in the relevant screen."],
    ["Narration", "Optional model-written wording. The underlying figures are deterministic; narration is not an independent source of financial facts."],
    ["Missing history", "No warning or an unavailable comparison is not proof everything is affordable. The app can only assess information you have entered."],
  ] },
  simulator: { title: "Your simulator", items: [
    ["Scenarios", "What-if plans based on the recorded position at the baseline date. They never post transactions or change your real balances."],
    ["Monthly income, fixed costs and spending", "Hypothetical recurring amounts. Check that the same cost is not included in two fields. These estimates are not bank facts."],
    ["Savings and investment", "Planned transfers in the scenario. Actual projected transfers are limited by available money. Investment return cases are assumptions, not promises."],
    ["Growth, inflation and income loss", "Change future income/cost assumptions or model a temporary payment gap. A zero rate means no assumed growth, not no uncertainty."],
    ["One-off costs and horizon", "One-offs apply in their specified month, counted from zero. Horizon is how many months to simulate."],
    ["Comparison and chart", "Compare two assumption sets against the same recorded baseline. Inspect individual months to see cash, savings and investment effects."],
    ["Notes and Delete", "Notes explain your assumptions. Deleting a scenario removes only that hypothetical plan, not actual transactions."],
  ] },
  import: { title: "Your imports", items: [
    ["Account and file profile", "Select the account the statement belongs to and the matching file format. A wrong account can create misleading balances when rows are accepted."],
    ["Upload / receipt", "Parses a statement or receipt into candidates for review. Uploading alone does not affect your ledger."],
    ["Candidates and suggestions", "Proposed dates, amounts, merchants and categories—not verified facts. Check receipt/model suggestions against the source."],
    ["Duplicates", "Potential repeats are flagged to avoid counting the same payment twice. Review the match rather than accepting both."],
    ["Accept, reject and reopen", "Accept creates a posted transaction and changes figures. Reject leaves it out. Reopen returns a rejected candidate to review."],
    ["Batch counts", "Pending, accepted, rejected and duplicate counts describe processing status, not extra transactions or balances."],
  ] },
  data: { title: "Your data and backups", items: [
    ["Exports", "Download reports or a portable backup. Reports are not necessarily full-fidelity restore files."],
    ["Backup now and scheduled backups", "Save a snapshot of application data. Backups contain financial information; keep them private. They do not contain the app's password configuration."],
    ["Latest backup and age", "Shows when a backup was written. A stale warning means protection may be out of date; no backup means nothing has been saved yet."],
    ["Restore preview", "Inspect the file and counts before restoring. Previewing does not alter your data."],
    ["Replace existing data", "Restore with replacement overwrites the active financial dataset. Verify the source and keep a suitable backup before proceeding."],
  ] },
};

export const FIELD_HELP: Record<string, string> = {
  Name: "A recognisable label; it does not affect the calculation.",
  Amount: "Enter pounds and pence. The surrounding form determines whether this is an actual payment or a plan.",
  "Amount per period": "The allowance for one complete budget cycle, not your account balance.",
  Period: "How often the allowance resets. A calendar month and exactly 30 days are different.",
  Starts: "The first date this plan applies; no earlier allowance is invented.",
  "Anchor date": "The reference day for repeated fortnightly or 30-day cycles.",
  Rollover: "Choose whether surplus or overspending carries into the next cycle.",
  Scope: "The category this budget covers; no category means all discretionary spending.",
  Ends: "The last date the plan applies. Leave empty for an ongoing plan.",
  Category: "Connects spending to budgets and reports. It does not change the amount paid.",
  "Target amount": "How much you aim to accumulate, not money already saved.",
  "Monthly contribution": "An intended monthly allocation. It reduces safe to spend but does not move money.",
  "Target date": "Your desired deadline; reaching it still depends on funding the goal.",
  Priority: "Critical/High goals are protected by default; Medium/Optional are flexible.",
  "Savings account": "Where the real savings are held; goal attribution cannot exceed its balance.",
  "First due": "The first expected payment date, which anchors repeated commitments.",
  Repeats: "Generates later expected occurrences, not actual paid transactions.",
  Treatment: "Hard commitments reduce safe to spend. Optional commitments do not.",
  Date: "The actual booking date used for balances and reporting periods.",
  Description: "A short explanation so you can recognise this transaction later.",
  "Merchant / payer": "Who you paid or received money from; useful for grouping and duplicate review.",
  "Paid from": "The account whose balance should decrease.",
  From: "The account the money leaves.",
  To: "The account the money enters.",
  "Expense account": "The bookkeeping destination that records what the payment cost; it is not another bank account.",
  "Income source": "The bookkeeping source of received money, such as your stipend; it is not an additional cash balance.",
  "Refund from": "The original expense account being reduced by this repayment.",
  "Opening balance": "The actual balance when you start tracking. Earlier purchases already included in it must not be deducted again.",
  "First expected": "The date you expect the next payment. It does not record the payment as received.",
  "Received into": "The account where actual income will arrive; an expected-income entry does not change its balance.",
};
